name: Test Game run
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-run:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      - name: Install build tools (windows)
        shell: cmd
        run: choco install -y make mingw
      - name: Set up environment variables
        shell: cmd
        run: |
          # echo "WORKFLOWS=lib/x64" >> "$GITHUB_ENV"
          echo "{WORKFLOWS}={lib/x64}" >> $GITHUB_ENV
      - name: Build the project
        shell: cmd
        run: |
          make SHELL=cmd.exe .SHELLFLAGS=/c all
